### PR TITLE
Axes without names

### PR DESCRIPTION
**Pull request by shaiTheKimhi**
This contains few changes that Moshe asked for.
First is addition of a display of the vector from both the location of the satellite and from point zero.
Second is the addition of axes.
Third is an ability to alter the size of the canvas to a certain size relative to the screen, with different ratios between the canvas size and the screen size for width and height.

### CODE REVIEW

**Comment by yotam180** [comment]
I think it's time to discuss the software and stop the sole development so not any more time is wasted...

**Comment by shaiTheKimhi** [comment]
These are just changes that Moshe asked for in the simulation, and so I made them.
I agree that we should discuss about the software before rushing, but these changes were requested a week ago, and completed two days ago.

**Comment by yotam180** [comment]
Sure

**Comment by shaiTheKimhi** [comment]
That was a quick answer.

**Comment by yotam180** [comment]
Well... When I'm online I usually respond quickly...

**Pull request closed without merging**
